all:
    hosts:
    staging:
        ansible_connection: ssh
        ansible_user: kobe
        ansible_host: 192.168.0.30
        ansible_port: 22
    production:
        ansible_connection: ssh
        ansible_user: kobe
        ansible_host: 192.168.0.30
        ansible_port: 22