- hosts: staging
  remote_user: kobe
  become: yes
  tasks:
  
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']

  - name: Add Docker GPG apt Key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    
  - name: Add Docker Repository
    apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
    
  - name: Update apt and install docker-ce
    apt: name=docker-ce

  - name: start docker service
    service:
        name: docker
        state: started  

  - name: setup ufw(Firewall Ubuntu)
    ufw:
        rule: allow
        port: '80'
        src: 127.0.0.1
        proto: tcp 

  - name: Get infos on container
    docker_container_info:
      name: webApp-prod
    register: result

  - name: Remove previous build
    shell: docker stop webApp && docker rm webApp && docker rmi kobeap/calendar-manager:latest
    when: result.exists

  - name: Create new webApp container
    docker_container:
      name: webApp
      image: kobeap/calendar-manager:latest
      ports:
      - "80:80"
